networks:
  default:
  wazuh-net:
    external: true
    name: wazuh-stack-single-node_default

services:
  redash-server:
    image: redash/redash:latest
    hostname: redash-server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - default
      - wazuh-net
    volumes:
      - ./elasticsearch.py:/app/redash/query_runner/elasticsearch.py:ro
    environment:
      REDASH_DATABASE_URL: "postgresql://redash:redash@redash-postgres/redash"
      REDASH_REDIS_URL: "redis://redash-redis:6379/0"
      REDASH_SECRET_KEY: "redash-secret-key-change-me-2026"
      REDASH_COOKIE_SECRET: "redash-cookie-secret-change-me-2026"
      PYTHONUNBUFFERED: "0"
      REDASH_LOG_LEVEL: "INFO"
      REQUESTS_CA_BUNDLE: ""
      PYTHONHTTPSVERIFY: "0"
    depends_on:
      - redash-postgres
      - redash-redis

  redash-scheduler:
    image: redash/redash:latest
    hostname: redash-scheduler
    restart: always
    command: scheduler
    environment:
      REDASH_DATABASE_URL: "postgresql://redash:redash@redash-postgres/redash"
      REDASH_REDIS_URL: "redis://redash-redis:6379/0"
      REDASH_SECRET_KEY: "redash-secret-key-change-me-2026"
      REDASH_COOKIE_SECRET: "redash-cookie-secret-change-me-2026"
      QUEUES: "celery"
      WORKERS_COUNT: "1"
    depends_on:
      - redash-postgres
      - redash-redis

  redash-worker:
    image: redash/redash:latest
    hostname: redash-worker
    restart: always
    command: worker
    networks:
      - default
      - wazuh-net
    volumes:
      - ./elasticsearch.py:/app/redash/query_runner/elasticsearch.py:ro
    environment:
      REDASH_DATABASE_URL: "postgresql://redash:redash@redash-postgres/redash"
      REDASH_REDIS_URL: "redis://redash-redis:6379/0"
      REDASH_SECRET_KEY: "redash-secret-key-change-me-2026"
      REDASH_COOKIE_SECRET: "redash-cookie-secret-change-me-2026"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: "2"
      REQUESTS_CA_BUNDLE: ""
      PYTHONHTTPSVERIFY: "0"
    depends_on:
      - redash-postgres
      - redash-redis

  redash-postgres:
    image: postgres:15-alpine
    hostname: redash-postgres
    restart: always
    environment:
      POSTGRES_USER: redash
      POSTGRES_PASSWORD: redash
      POSTGRES_DB: redash
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redash-redis:
    image: redis:7-alpine
    hostname: redash-redis
    restart: always
    volumes:
      - ./data/redis:/data
