events {
    worker_connections 1024;
}

stream {
    upstream wazuh_agents {
        hash $remote_addr consistent;
        server wazuh.master:1514;
        server wazuh.worker:1514;
    }
    server {
        listen 1514;
        proxy_pass wazuh_agents;
    }

    upstream syslog_cluster {
        hash $remote_addr consistent;
        server wazuh.master:514;
        server wazuh.worker:514;
    }
    server {
        listen 514 udp;
        proxy_pass syslog_cluster;
        proxy_responses 0;
    }
}
